"""Terms used by the rules scorer. Edit this list rather than the scoring formula."""

GHANA_STRONG: tuple[str, ...] = (
    "ghana",
    "ghanaian",
    "ghanaians",
    "accra",
    "kumasi",
    "tamale",
    "takoradi",
    "cape coast",
    "sunyani",
    "koforidua",
    "bolgatanga",
    "techiman",
    "winneba",
    "ashanti",
    "greater accra",
    "ghana education service",
    "ges",
    "gtec",
    "waec",
    "nacca",
    "ministry of education",
    "free shs",
    "ctvet",
    "gnat",
    "nagrat",
    "gnecc",
    "ncpta",
    "tewu",
)

EDUCATION_STRONG: tuple[str, ...] = (
    "teacher",
    "teachers",
    "student",
    "students",
    "university",
    "universities",
    "curriculum",
    "scholarship",
    "scholarships",
    "admission",
    "admissions",
    "bece",
    "wassce",
    "shs",
    "jhs",
    "tvet",
    "headteacher",
    "head teacher",
    "headmaster",
    "classroom",
    "classrooms",
    "kindergarten",
    "education",
    "lecturer",
    "lecturers",
    "pupil",
    "pupils",
    "ges",
    "ghana education service",
    "gtec",
    "waec",
    "school feeding",
    "senior high",
    "junior high",
    "basic school",
    "matriculation",
    "graduation",
    "gnat",
    "nagrat",
    "gnecc",
    "ncpta",
    "tewu",
)

EDUCATION_WEAK: tuple[str, ...] = (
    "school",
    "schools",
    "class",
    "classes",
    "academic",
    "exam",
    "exams",
)
